### ISSUE TITLE
4.13.0-0.okd-scos-2023-10-19-111256 bootstrap problems

### ISSUE THREAD

**Issue by luenta** [okd-project/okd-scos#14]
Tried to install new cluster bare-metal with the latest installer. Got many issues during master bootstrapping.
For example sdn pods stuck on recreating, and the logs said: _/bin/bash: line 49: "RHEL_VERSION:" unbound variable_

Found the issue solved here: https://github.com/openshift/cluster-network-operator/pull/2003/commits/9f83883307ce7b6046b5b2d76895e5ddcca24e3b#diff-ec483261857ecc5887c65ea0a5eddfb3f7768ac3cef206e99599bd82e140accb

When I edited the specified yaml s some processes went trough, but eventually they were set default ( for example the sdn by the network operator ) 

Any idea to workaround? Or will this be fixed soon?
Thanks!

**Comment by apmlima** [comment]
Same occurs to me also and when checking the log bundle also found:
* systemd-sysusers.service loaded failed failed Create System Users

Wondering if this project still alive or someone supporting this issues?!?

**Comment by dbenoit17** [comment]
I hit this issue as well, and seems like 4.14 picks up the cluster-network-operator fix.  I was able to deploy 4.14.0-0.okd-scos-2023-10-11-044258 (pre-release) without issues.

**Comment by LorbusChris** [comment]
The next stable release will probably move to 4.14, which will include this fix as mentioned. We won't backport to 4.13 at this point.

**Comment by luenta** [comment]
https://github.com/openshift/cluster-network-operator/pull/2086

Am I allowed to try to fix like this or did I touch some holy magic that I shouldn't have?

**Comment by LorbusChris** [comment]
Thanks for stepping up @luenta! PRs are always welcome, but unfortunately backports require additional QE scrutiny, so it won't be done at this point. OKD 4.14 will be out soon, so please stay tuned.
